# Site settings
title: Hagyeong Kim
job_title: Software Programmer
email: digipen.hagyeong@gmail.com
url: https://hagyeongkimdigipen.github.io/Hagyeong/
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
skills: "C++, C#, C, Python, GLSL, HTML, Unity, Unreal Engine, AR Foundation,<br/>OpenGL, VSCode, Visual Studio, Github, Source Tree"
meta_author: Hagyeong Kim

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 50586C  
  primary-rgb: "80, 88, 108" 
  secondary: DCE2F0 
  secondary-dark: B0B5C0

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/hagyeong-kim-59827721a/
  - title: github
    url: https://github.com/HagyeongKimDigipen

# Postal address (add as many lines as necessary)
address:
  - line: NE 90th Street 
  - line: Redmond, WA 

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
